@host = http://127.0.0.1:3000

### Root

###
GET {{ host }} HTTP/1.1
Content-Type: application/json

### Significant Digits

###
GET {{ host }}/significant-digits?input=0 HTTP/1.1
Content-Type: application/json

###
GET {{ host }}/significant-digits?input=0.000 HTTP/1.1
Content-Type: application/json

###
GET {{ host }}/significant-digits?input=3.4 HTTP/1.1
Content-Type: application/json

###
GET {{ host }}/significant-digits?input=300. HTTP/1.1
Content-Type: application/json

###
GET {{ host }}/significant-digits?input=0.0055443 HTTP/1.1
Content-Type: application/json

###
GET {{ host }}/significant-digits?input=0.00244400 HTTP/1.1
Content-Type: application/json

### Bisection

### Route below has an eror where f(a) and f(b) does not have opposing signs.
GET {{ host }}/bisection?expression=x^3 - 4x^2 - 10&start=1&end=3 HTTP/1.1
Content-Type: application/json

### Route below has an error of REST Client where plus sign is not getting encoded.
GET {{ host }}/bisection?expression=x^3 + 4x^2 - 10&start=1&end=2&iteration=20&dp=8 HTTP/1.1
Content-Type: application/json

### Route below has an error where `start` is greater than `end`, should return 400
GET {{ host }}/bisection?expression=x^3 -x - 10&start=2&end=1&iteration=20&dp=8 HTTP/1.1
Content-Type: application/json

### Route below has both start greater than end error and opposing sign error. But start greater than end error
### should appear first since we check those first.
GET {{ host }}/bisection?expression=x^3 - 4x^2 - 10&start=2&end=1 HTTP/1.1
Content-Type: application/json

### False Position

###
GET {{ host }}/false-position?expression=x^2 - x - 1&start=-2&end=0&iteration=20&dp=7 HTTP/1.1
Content-Type: application/json

###
GET {{ host }}/false-position?expression=x^3 - 2&start=1&end=2&iteration=10 HTTP/1.1
Content-Type: application/json

### Fixed Point Iteration

###
GET {{ host }}/fixed-point-iteration?expression=x^2 - x - 1&fixedExpression=1 %2b %281 %2F x%29&start=2&iteration=20&dp=7 HTTP/1.1
Content-Type: application/json

### Newton

### Normal route
GET {{ host }}/newton?expression=x^3 - 4x^2 %2B 1&diffedExpression=3x^2 - 8x&respect=x&start=0.5&iteration=20&dp=7 HTTP/1.1
Content-Type: application/json

### Also works without diffedExpression
GET {{ host }}/newton?expression=x^3 - 4x^2 %2B 1&respect=x&start=0.5&iteration=20&dp=7 HTTP/1.1
Content-Type: application/json

### Also works without respect
GET {{ host }}/newton?expression=x^3 - 4x^2 %2B 1&respect=x&start=0.5&iteration=20&dp=7 HTTP/1.1
Content-Type: application/json
