@host = http://127.0.0.1:3000

GET {{ host }} HTTP/1.1
Content-Type: application/json

###
GET {{ host }}/significant-digits/amount?input=4250 HTTP/1.1
Content-Type: application/json

### Route below has an eror where f(a) and f(b) does not have opposing signs.
GET {{ host }}/bisection?expression=x^3 - 4x^2 - 10&start=1&end=3 HTTP/1.1
Content-Type: application/json

### Route below has an error of REST Client where plus sign is not getting encoded.
GET {{ host }}/bisection?expression=x^3 + 4x^2 - 10&start=1&end=2&iteration=20&dp=8 HTTP/1.1
Content-Type: application/json

### Route below has an error where `start` is greater than `end`, should return 400
GET {{ host }}/bisection?expression=x^3 -x - 10&start=2&end=1&iteration=20&dp=8 HTTP/1.1
Content-Type: application/json

### Route below has both start greater than end error and opposing sign error. But start greater than end error
### should appear first since we check those first.
GET {{ host }}/bisection?expression=x^3 - 4x^2 - 10&start=2&end=1 HTTP/1.1
Content-Type: application/json
